services:
  pgadmin:
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    # depends_on:
    #   - postgres-db
    networks:
      dev-network:

networks:
  dev-network: